### ISSUE TITLE
navbar: uneven spacing of outer button elements on small viewport

### ISSUE THREAD

**Issue by aslink87** [eddb2-0/EDDB-2.0-frontend#101]
480px (Chakra small): 
Burger menu and color theme button have uneven outer spacing:

![Screenshot 2023-09-04 at 15-22-33 EDPN - Commodities](https://github.com/ed-pilots-network/frontend/assets/67390534/9e0fd5fe-dd5d-495b-ba16-e07aec972dbf)

**Comment by jbritain** [comment]
Unless anyone else wants it I'll do this one!
