### ISSUE TITLE
Identify and include an extensive icons library that can work for EDPN use case for the interim

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#31]
Charka icons pool is pretty small and won't be enough for our use case

We can follow Chakra recommendations for 3P icons here - https://chakra-ui.com/docs/components/icon/usage

https://react-icons.github.io/react-icons/ is a good option as it lets developers search the icon by name / theme and can show suggestions across what's available in react-icons. For the time we are in development, we can use this to move fast and once we know what we need, we can optimize and only extract and import the ones we need as a smaller package

**Comment by aslink87** [comment]
I second React Icons. It collates several large icon libraries into one place.
