### ISSUE TITLE
Setup a navigation component (responsive)

### ISSUE THREAD

**Issue by aslink87** [eddb2-0/EDDB-2.0-frontend#35]
Until the app gets more fleshed out, a 'nav component' can be accomplished via a home page card directory that directs users to different areas of the app. In the future, as we add more features (probably after v1) a navbar with links may be required. This issue will need ongoing maintenance.

**Comment by aslink87** [comment]
Linked branch: [card-navigation](https://github.com/ed-pilots-network/frontend/tree/card-navigation)

I'd like to get some discussion and opinions here as I know others are working on this as well. Even if we decide to merge this branch, the work others have done can be added to, or replace, what's in this branch.

So before I consider making a PR, please take a moment to share your thoughts on merging this. Do you like the tab navigation? What about the light theme colors? I tried to grab some inspiration from the official E:D website.

Please keep in mind the cards can be changed as well as the bg images. I just took a few minutes to come up with the current images.

Here's some images to save you some time.


![Image](https://github.com/ed-pilots-network/frontend/assets/67390534/71175960-cbc2-4136-a489-d92cb809ac73)


![Image](https://github.com/ed-pilots-network/frontend/assets/67390534/be214ad5-7a6d-41fd-b747-8ef2d70cf50a)

**Comment by Gutto1** [comment]
I like this approach of cards and tabs to serve as a link to the content pages. It's clean and easy to understand. I prefer this minimalist ideia with icons and text over the ideia with cards using bg images, but it's just a personal preference

**Comment by westonnovelli** [comment]
Works for me! It should be simple enough to evolve over time if we end up not liking it.

**Comment by jbritain** [comment]
I like this, one thing I think you could change would be making the borders on the cards a bit more subtle. I was never a massive fan of the aesthetics of the original EDDB and I think the very solid borders were part of the reason for that.

**Comment by aslink87** [comment]
@jbritain 
I get what your saying, and would also like to see it toned down. They are at 1px now so perhaps we can set an opacity or something to them. I merged the PR as is, perhaps we can try some different techniques to this?
