### ISSUE TITLE
Setup proxy to call hosted API endpoints on morris from local development

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#49]
Setup proxy to call hosted API endpoints on morris from local development

**Comment by aslink87** [comment]
morris is the dev backend host name correct?
Could you explain a bit on how you envision the local development env resembling prod regarding API calls? And how will the local JSON server fit into it.

**Comment by nitishdhar** [comment]
> morris is the dev backend host name correct?

yes

> Could you explain a bit on how you envision the local development env resembling prod regarding API calls? And how will the local JSON server fit into it.

I have posted a PR with details on this https://github.com/ed-pilots-network/frontend/pull/54. We can use the json one as and when needed when working locally.
