### ISSUE TITLE
Custom form components use hard coded colors, should pick from a config instead

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#57]
Custom form components use hard coded colors, should pick from a config instead

**Comment by aslink87** [comment]
Could you provide an example please?

**Comment by nitishdhar** [comment]
Yeah, if you look at the components added under theme, they use certain colors that are common across. These should be controlled from a central config parameter. e.g. this new blue theme that we are using in the forms

<img width="294" alt="Screen Shot 2023-08-05 at 11 13 42 PM" src="https://github.com/ed-pilots-network/frontend/assets/1340144/a20cb211-ae7a-4c4b-b1e4-e06a9212e5c2">

**Comment by nitishdhar** [comment]
Was fixed with this PR - https://github.com/ed-pilots-network/frontend/pull/94

**Comment by nitishdhar** [comment]
> Could you provide an example please?

@aslink87 Thanks for fixing this
