### ISSUE TITLE
Auto-"go forwards" on link hover or click

### ISSUE THREAD

**Issue by madmax-codewarrior-0** [eddb2-0/EDDB-2.0-frontend#83]
If visiting a page on oscar.edpn.io that is incomplete (404; E.g. /bodies, /pois, /attractions, etc.), and returning to the main page via the browser's back button (or similar key/macro), hovering over any link or clicking a menu item will "push the navigation of history forward", effectively revisiting the same page from whence one just came, without selecting any new link to a page. See frustrations below.

![go-back-no-wait-whut](https://github.com/ed-pilots-network/frontend/assets/58088316/a88853b2-d640-4bb1-ace5-5742b1f3be97)

Fedora Linux 37 - 6.4.9-100.fc37.x86_64
Brave Browser Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

**Comment by chrismou** [comment]
I can only seem to recreate this on Firefox, doesn't seem to be an issue for me on chrome. Can anyone else confirm?

**Comment by nitishdhar** [comment]
I had seen this issue like a few weeks ago and I think we discussed this in the channel also but now I can't seem to reproduce it anymore (Tried on FireFox & Edge on Mac). I will check on my Windows in a bit, I might have seen this on Windows.

**Comment by nitishdhar** [comment]
Ok, can reproduce this on Mobile (iOS) Edge Browser, Chrome and Safari

**Comment by chrismou** [comment]
@nitishdhar Chrome only on windows or everywhere?

**Comment by nitishdhar** [comment]
@chrismou all on mobile - edge, chrome and safari browsers

**Comment by nitishdhar** [comment]
Related issues & references - 

- https://www.reddit.com/r/nextjs/comments/13kwcax/the_app_router_is_not_productionready_yet/
- https://github.com/vercel/next.js/pull/49855
- https://stackoverflow.com/questions/76585950/nextjs-not-found-page-keeps-reloading-every-3-seconds
- https://github.com/vercel/next.js/issues/10024

**Comment by nitishdhar** [comment]
Leveraging this fix until they fix it under the hood - https://github.com/vercel/next.js/discussions/40000#discussioncomment-6291368
