### ISSUE TITLE
Tree shaking for react-icons isn't working in local development. Loads all icon modules

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#84]
Tree shaking for react-icons isn't working in local development. Loads all icon modules

Works fine for the production build.

`event compiled client and server successfully in 41.4s (2653 modules)`

![Screen Shot 2023-08-11 at 10 51 05 PM](https://github.com/ed-pilots-network/frontend/assets/1340144/ffd40498-654f-4555-985c-f29a308a9c80)

Refer - https://github.com/react-icons/react-icons/issues/154

Also Refer - https://github.com/vercel/next.js/issues/48748

**Comment by nitishdhar** [comment]
PR for fix is open with that library - https://github.com/react-icons/react-icons/pull/727

**Comment by aslink87** [comment]
I've created the [icon-lag-testing](https://github.com/ed-pilots-network/frontend/tree/icon-lag-testing) branch to sandbox some potential resolutions as there has been little activity on that PR from the maintainers. Which is disappointing.

icon-lag-testing branch currently has moved all of our icons to fontAwesome from react-icons. Total unzipped client size compared to development branch with same codebase is 3.7mb vs 14.3mb. Zipped size is larger with 372.9kb vs 356.9kb on development.

I suggest we test using the icon-lag-testing branch to see the impact on developer experience. If this difference is noticeable then we should merge it into all active main branches and eliminate using react-icons in the future.
